### ISSUE TITLE
Disable creating readme and updating package.json on postinstall 

### ISSUE THREAD

**Issue by theoparis** [CTNicholas/tauque#1]
Hi there. I have a pnpm monorepo containing a structure like this:

- root project 
  - packages/
     - some-bundled-package
     - another-bundled-package
  
Because tauque updates the package.json with some scripts and a taeque.readme file, it causes the files to be written to the root project, which is annoying. I don't want to have to keep removing these from the package.json, and adding these two files to .gitignore every time i run pnpm install.

Overall though, very nice project :)

**Comment by CTNicholas** [comment]
Hey, thanks for the feedback! I've just updated Tauque, and also created a separate installer, take a look [here](https://github.com/CTNicholas/tauque/releases/tag/v1.4).

Let me know if that works for you :)
